projects/mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('hello/', include('hello.urls')),
]

projects/mysite/hello/urls.py
from django.urls import path, include
from .views import HELLoAPI

urlpatterns = [
	path("hello/", HELLoAPI),
]

projects/mysite/pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
	path('', views.index, name ='index'),
	path('<int:question_id>/', views.detail, name='detail'),
	path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
	path('question/create/', views.question_create, name='question_create'),
]

projects/mysite/hello/models.py
from django.db import models

# Create your models here.

projects/mysite/pybo/models.py
from django.db import models

class Question(models.Model):
	subject = models.CharField(max_length=200)
	content = models.TextField()
	create_date = models.DateTimeField()
	
	def __str__(self):
		return self.subject

class Answer(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	content = models.TextField()
	create_date = models.DateTimeField()
# Create your models here.

projects/mysite/pybo/forms.py
from django import forms
from pybo.models import Question

class QuestionForm(forms.ModelForm):
	class Meta:
		model = Question
		fields = ['subject', 'content']

projects/mysite/hello/views.py
from rest_framework import viewsets, permissions, generics, status
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.decorators import api_view

@api_view(['GET'])
def HELLoAPI(request):
	return Response("hello world")

projects/mysite/pybo/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.http import HttpResponse
from .models import Question
from django.utils import timezone
from .forms import QuestionForm

def index(request):
	"""
	pybo 목록 출력
	"""
	question_list = Question.objects.order_by('-create_date')
	context = {'question_list': question_list}
	return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	context = {'question': question}
	return render(request, 'pybo/question_detail.html', context)
# Create your views here.

def answer_create(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
	return redirect('pybo:detail', question_id=question_id)

def question_create(request):
	if request.method == 'POST':
		form = QuestionForm(request.POST)
		if form.is_valid():
			question = form.save(commit=False)
			question.create_date = timezone.now()
			question.save()
			return redirect('pybo:index')
	else:
		form = QuestionForm()
	return render(request, 'pybo/question_form.html', {'form': form})

projects/mysite/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>파이보</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

projects/mysite/templates/pybo/question_detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" >
<h1>{{question.subject}}</h1>

<div>
	{{question.content}}
</div>

<h5>{{question.answer_set.count}} 개의 답변이 있습니다.</h5>
<div>
	<ul>
		{% for answer in question.answer_set.all %}
			<li>{{answer.content}}</li>
		{% endfor %}
	</ul>
</div>

<form action="{% url 'pybo:answer_create' question.id %}" method="post">
{% csrf_token %}
<textarea name="content" id="content" rows="15"></textarea>
<input type="submit" value="답변 등록">
</form>

projects/mysite/templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
	<h5 class="my-3 border-bottom pb-2">질문등록</h5>
	<form method="post" class="post-form my-3">
		{% csrf_token %}
		{{ form.as_p}}
		<button type="submit" class="btn btn-primary">저장하기</button>
	</form>
</div>

{% endblock %}

projects/mysite/templates/pybo/question_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
	<table class="table">
		<thead>
			<tr class="thead-dark">
				<th>번호</th>
				<th>제목</th>
				<th>작성일지</th>
			</tr>
		</thead>
		<tbody>
		{% if question_list %}
		{% for question in question_list %}
		<tr>
			<td>{{forloop.counter}}</td>
			<td>
				<a href="{% url 'pybo:detail' question.id %}">
				{{question.subject}}
				</a>
			</td>
			<td>{{question.create_date}}</td>
		</tr>
		{% endfor %}
		{% else %}
		<tr>
			<td colspan="3">질문이 없습니다</td>
		</tr>
		{% endif %}
		</tbody>
	</table>
	<a href="{% url 'pybo:question_create' %}" class="btn btn-primary">
		질문등록하기
	</a>
</div>

<!-- {% if question_list %}
 	<ul>
 	{% for question in question_list %}
		<li><a href="{% url 'pybo:detail' question.id %}">{{question.subject}}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>질문이 없습니다.</p>
{% endif %} -->

{% endblock %}